//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donate
{
    using System;
    using System.Collections.Generic;
    
    public partial class donation
    {
        public int id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> @object { get; set; }
        public Nullable<decimal> money { get; set; }
        public string donor { get; set; }
        public string message { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual @object object1 { get; set; }
        public virtual type type1 { get; set; }
    }
}
