//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donate
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int id { get; set; }
        public string self_id { get; set; }
        public string parent_id { get; set; }
        public string name { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> status { get; set; }
        public string url { get; set; }
        public string icon { get; set; }
    }
}
