//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donate
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemInfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string domain { get; set; }
        public Nullable<double> cache { get; set; }
        public Nullable<double> max_file_size { get; set; }
        public string file_type { get; set; }
        public string title { get; set; }
        public string keywords { get; set; }
        public string description { get; set; }
        public string copyright { get; set; }
    }
}
