//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donate
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int uid { get; set; }
        public string nick { get; set; }
        public Nullable<int> gender { get; set; }
        public string imgUrl { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public Nullable<int> role { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> lastDate { get; set; }
        public string password { get; set; }
        public string lastIp { get; set; }
        public Nullable<int> isAut { get; set; }
    
        public virtual role role1 { get; set; }
    }
}
